services:
  - type: web
    name: fastapi-hello
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fastapi-books-db
          property: connectionString

databases:
  - name: fastapi-books-db
    plan: free
